name: safe_sky
description: Safe Sky

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  provider: ^6.0.3
  mobile_scanner: ^3.4.0
  flutter_map: ^4.0.0
  slide_to_act: ^2.0.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_map_tile_caching: ^8.0.1
  pull_to_refresh: ^2.0.0









flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/auth_back.png
    - assets/svg/logo.svg

flutter_gen_l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart


