name: Build APK

on:
  push:
    branches:
      - develop
      - release
    tags-ignore:
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ github.event.head_commit.message }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Localization Files
        run: flutter gen-l10n

      - name: Run server build script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"  # отладочный вывод
          chmod +x ./build_server.sh
          FLAG=$(echo "${{ github.event.head_commit.message }}" | grep -oP '\[BUILD_FLAG:\K[^]]+')
          if [ -z "$FLAG" ]; then
            FLAG="-at"
          fi
          COMMAND="build"
          ./build_server.sh "$COMMAND" "$FLAG"
