name: Build APK

on:
  push:
    branches:
      - master
      - staging
  workflow_dispatch:
    inputs:
      command:
        description: "Команда: run (локальный запуск) или build (серверная сборка)"
        required: true
        default: build
      flag:
        description: "Флаг: -t (тест) или -p (production). Необязателен для master."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Localization Files
        run: flutter gen-l10n

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh "${{ github.event.inputs.command }}" "${{ github.event.inputs.flag }}"
