name: Build APK

on:
  push:
    branches:
      - develop
    tags-ignore:
      - 'v*'
  workflow_dispatch:
    inputs:
      command:
        description: "Команда: run (локальный запуск) или build (серверная сборка)"
        required: true
        default: build
      flag:
        description: "Флаг: -at, -ap, -bt, -bp, -t, -p"
        required: true

concurrency:
  group: build-develop
  cancel-in-progress: true

jobs:
  build:
    # Запускаем только если событие – push в ветку, а также чтобы запускался только последний commit
    if: startsWith(github.ref, 'refs/heads/') && (github.event.after == github.sha)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Localization Files
        run: flutter gen-l10n

      - name: Run server build script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          chmod +x ./build_server.sh
          # При событии workflow_dispatch используем входные параметры,
          # иначе для push-события оставляем FLAG пустым (build_server.sh извлечёт его из commit message)
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            FLAG="${{ github.event.inputs.flag }}"
            COMMAND="${{ github.event.inputs.command }}"
          else
            COMMAND="build"
            FLAG=""
          fi
          ./build_server.sh "$COMMAND" "$FLAG"
