name: Build APK

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Команда: run или build (серверная сборка)"
        required: true
        default: build
      flag:
        description: "Флаг: -at, -ap, -bt, -bp, -t, -p"
        required: true
      workflow_name:
        description: "Имя для отображения в job"
        required: false
        default: "Build APK"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ github.event.inputs.workflow_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Localization Files
        run: flutter gen-l10n

      - name: Run server build script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"  # отладочный вывод
          chmod +x ./build_server.sh
          FLAG="${{ github.event.inputs.flag }}"
          COMMAND="${{ github.event.inputs.command }}"
          ./build_server.sh "$COMMAND" "$FLAG"
