name: Flutter CI

on:
  push:
    branches:
      - master  # Запускать только при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Bump version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | sed 's/version: //')
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$3+=1; print}')
          sed -i "s/version: .*/version: $NEW_VERSION/" pubspec.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "CI: Bump version to $NEW_VERSION"
          git push origin master

      - name: Build APK
        run: flutter build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
